package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/pkg/errors"
	"golang.org/x/tools/go/packages"
)

const (
	commentTag  = "// generate:reset"
	genFileName = "reset.gen.go"
)

type fieldInfo struct {
	Name string
	Code string
}

type structInfo struct {
	Name   string
	Fields []fieldInfo
}

type packageData struct {
	Name    string
	Dir     string
	Structs []structInfo
}

const resetTmpl = `
// Code generated by reset-gen. DO NOT EDIT.
package {{.Name}}

{{range .Structs}}
func (r *{{.Name}}) Reset() {
	if r == nil {
		return
	}
{{range .Fields}}
	{{.Code}}
{{end}}
}
{{end}}
`

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedName | packages.NeedFiles | packages.NeedTypes,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("load packages error: %v", err)
	}

	for _, pkg := range pkgs {
		processPackage(pkg)
	}
}

func processPackage(pkg *packages.Package) {
	data := packageData{Name: pkg.Name, Dir: pkg.Dir}

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE || !hasTag(gd) {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				info := structInfo{Name: ts.Name.Name}
				for _, field := range st.Fields.List {
					for _, name := range field.Names {
						info.Fields = append(info.Fields, fieldInfo{
							Name: name.Name,
							Code: genFieldReset("r."+name.Name, field.Type),
						})
					}
				}
				data.Structs = append(data.Structs, info)
			}
		}
	}

	if len(data.Structs) != 0 {
		if err := generateFile(data); err != nil {
			log.Fatalf("generate file error: %v", err)
		}
	}
}

func hasTag(gd *ast.GenDecl) bool {
	if gd.Doc == nil {
		return false
	}

	for _, c := range gd.Doc.List {
		if strings.Contains(c.Text, commentTag) {
			return true
		}
	}

	return false
}

func genFieldReset(path string, expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if isPrimitive(t.Name) {
			return fmt.Sprintf("%s = %s", path, zeroValue(t.Name))
		}
		return fmt.Sprintf("if res, ok := any(%s).(interface{ Reset() }); ok { res.Reset() }", path)
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok && isPrimitive(id.Name) {
			return fmt.Sprintf("if %s != nil { *%s = %s }", path, path, zeroValue(id.Name))
		}
		return fmt.Sprintf("if %s != nil { if res, ok := any(%s).(interface{ Reset() }); ok { res.Reset() } }", path, path)
	case *ast.ArrayType:
		return fmt.Sprintf("%s = %s[:0]", path, path)
	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", path)
	default:
		return "// " + path + ": unsupported type"
	}
}

func isPrimitive(name string) bool {
	switch name {
	case "string", "bool", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128":
		return true
	}
	return false
}

func zeroValue(name string) string {
	if name == "string" {
		return `""`
	}
	if name == "bool" {
		return "false"
	}
	return "0"
}

func generateFile(data packageData) error {
	tmpl := template.Must(template.New("reset").Parse(resetTmpl))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return errors.Wrap(err, "execute template")
	}

	res, err := format.Source(buf.Bytes())
	if err != nil {
		return errors.Wrap(err, "format source")
	}

	outPath := filepath.Join(data.Dir, genFileName)
	fmt.Println(outPath)
	err = os.WriteFile(outPath, res, 0644)

	return errors.Wrap(err, "write file")
}
